require:
  - rubocop-rails
  - rubocop-minitest

# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  NewCops: enable
  Exclude:
  - '.internal_test_app/**/*'
  - 'app/controllers/concerns/spotlight/controller.rb'
  - 'bin/**/*'
  - 'config/routes.rb'
  - 'db/**/*'
  - 'Gemfile'
  - 'tmp/**/*'
  - 'vendor/**/*'
  - 'Rakefile'
  - 'lib/tasks/db_fixtures_dump.rake'
  - 'app/lib/umedia/citation/styles/schema_org.rb'

Layout/LineLength:
  Max: 120
  Exclude:
  - 'config/initializers/devise.rb'
  - 'config/initializers/spotlight_initializer.rb'
  - 'test/**/*'

Lint/ShadowedException:
  Exclude:
  - 'app/services/umedia/image_service.rb'

Metrics/BlockLength:
  Exclude:
  - 'app/controllers/catalog_controller.rb'
  - 'lib/tasks/umedia.rake'

Metrics/MethodLength:
  Exclude:
  - 'app/lib/umedia/citation/styles/coins.rb'
  - 'app/lib/umedia/citation/styles/mla.rb'
  - 'app/lib/umedia/citation/styles/wikipedia.rb'

Minitest/MultipleAssertions:
  Max: 20
