url: https://archive.apache.org/dist/lucene/solr/8.11.1/solr-8.11.1.zip
validate: false
instance_dir: tmp/solr
download_dir: tmp/solr
collection:
  dir: solr/conf/
  name: blacklight-core
  persist: true
solr_options:
  # Only allow Jetty to use the local adapter
  addlopts: "-Djetty.host=127.0.0.1 -Dlog4j2.formatMsgNoLookups=True"
