### UMedia field mappings
---
field_mappings:
  - dest_path: location
    origin_path: /
    formatters:
      - CDMDEXER::LocationFormatter

  - dest_path: id
    origin_path: id
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: object
    origin_path: id
    formatters:
      - Umedia::Formatters::ObjectFormatter

  - dest_path: set_spec
    origin_path: /
    formatters:
      - CDMDEXER::AddSetSpecFormatter
      - CDMDEXER::SetSpecFormatter

  - dest_path: collection_name
    origin_path: /
    formatters:
      - CDMDEXER::AddSetSpecFormatter
      - Umedia::Formatters::UmediaCollectionNameFormatter

  - dest_path: collection_description
    origin_path: /
    formatters:
      - CDMDEXER::AddSetSpecFormatter
      - CDMDEXER::CollectionDescriptionFormatter
      - CDMDEXER::FilterBadCollections

  - dest_path: super_collection_names
    origin_path: /
    formatters:
      - CDMDEXER::AddSetSpecFormatter
      - Umedia::Formatters::SuperCollectionNamesFormatter

  - dest_path: super_collection_set_specs
    origin_path: projea
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: super_collection_descriptions
    origin_path: /
    formatters:
      - CDMDEXER::AddSetSpecFormatter
      - Umedia::Formatters::SuperCollectionDescriptionsFormatter

  - dest_path: title
    origin_path: title
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: title_search
    origin_path: title
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: title_sort
    origin_path: title
    formatters:
      - CDMDEXER::StripFormatter
      - Umedia::Formatters::LetterSortFormatter

  - dest_path: title_alternative
    origin_path: altern
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: contributor
    origin_path: contri
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: creator
    origin_path: creato
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: creator_sort
    origin_path: creato
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::JoinFormatter
      - Umedia::Formatters::LetterSortFormatter

  - dest_path: description
    origin_path: descri
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: date_created
    origin_path: date
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: date_created_sort
    origin_path: date
    formatters:
      - CDMDEXER::StripFormatter
      - Umedia::Formatters::NumberSortFormatter

  - dest_path: historical_era
    origin_path: histor
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: publisher
    origin_path: publis
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: publishing_agency
    origin_path: publia
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: caption
    origin_path: captio
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: notes
    origin_path: additi
    formatters:
      - CDMDEXER::StripFormatter

  ###########################################
  # Physical Description
  ###########################################
  - dest_path: types
    origin_path: type
    formatters:
      - CDMDEXER::StripFormatter
      - CDMDEXER::Titlieze
      - CDMDEXER::SplitFormatter
      - CDMDEXER::UniqueFormatter

  - dest_path: format
    origin_path: format
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: format_name
    origin_path: format
    formatters:
      - Umedia::Formatters::FormatNameFormatter
      - CDMDEXER::StripFormatter

  - dest_path: dimensions
    origin_path: dimens
    formatters:
      - CDMDEXER::StripFormatter

  ###########################################
  # Topics
  ###########################################
  - dest_path: subject
    origin_path: subjec
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::SplitFormatter
      - Umedia::Formatters::SubjectFormatter
      - CDMDEXER::StripFormatter

  - dest_path: subject_fast
    origin_path: fast
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::SplitFormatter
      - Umedia::Formatters::SubjectFormatter
      - CDMDEXER::StripFormatter

  - dest_path: language
    origin_path: langua
    formatters:
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: alternate_languages
    origin_path: altera
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  ###########################################
  # Geographic
  ###########################################
  - dest_path: city
    origin_path: city
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: state
    origin_path: state
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: country
    origin_path: countr
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: region
    origin_path: region
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: continent
    origin_path: contin
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: geonames
    origin_path: geonam
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: projection
    origin_path: projec
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: scale
    origin_path: scale
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: coordinates
    origin_path: coordi
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  ###########################################
  # Collection Information
  ###########################################
  - dest_path: parent_collection
    origin_path: a
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: parent_collection_name
    origin_path: a
    formatters:
      - CDMDEXER::StripFormatter
      - Umedia::Formatters::SemiSplitFirstFormatter

  - dest_path: contributing_organization
    origin_path: contra
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::StripFormatter

  - dest_path: contributing_organization_name
    origin_path: contra
    formatters:
      - CDMDEXER::StripFormatter
      - Umedia::Formatters::SemiSplitFirstFormatter

  - dest_path: contact_information
    origin_path: contac
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: fiscal_sponsor
    origin_path: fiscal
    formatters:
      - CDMDEXER::StripFormatter

  ###########################################
  # Identifiers
  ###########################################
  - dest_path: local_identifier
    origin_path: identi
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: barcode
    origin_path: barcod
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: system_identifier
    origin_path: system
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: dls_identifier
    origin_path: dls
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: persistent_url
    origin_path: persis
    formatters:
      - CDMDEXER::StripFormatter

  ###########################################
  # Rights
  ###########################################
  - dest_path: local_rights
    origin_path: local
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: standardized_rights
    origin_path: standa
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: rights_statement_uri
    origin_path: righta
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: expected_public_domain_year
    origin_path: expect
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: additional_rights_information
    origin_path: addita
    formatters:
      - CDMDEXER::StripFormatter

  ###########################################
  # Transcript
  ###########################################
  - dest_path: transcription
    origin_path: transc
    formatters:
      - Umedia::Formatters::RemoveHashFormatter
      - CDMDEXER::StripFormatter

  - dest_path: translation
    origin_path: transl
    formatters:
      - CDMDEXER::StripFormatter

  ###########################################
  # Non-displayed fields
  ###########################################
  - dest_path: kaltura_audio
    origin_path: kaltur
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: kaltura_audio_playlist
    origin_path: kaltua
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: kaltura_video
    origin_path: kaltub
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: kaltura_video_playlist
    origin_path: kaltuc
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: kaltura_combo_playlist
    origin_path: kaltud
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: page_count
    origin_path: /
    formatters:
      - Umedia::Formatters::PageCountFormatter

  - dest_path: record_type
    origin_path: record_type
    formatters: []

  - dest_path: parent_id
    origin_path: parent_id
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: first_viewer_type
    origin_path: /
    formatters:
      - Umedia::Formatters::FirstViewerTypeFormatter

  - dest_path: viewer_type
    origin_path: /
    formatters:
      - Umedia::Formatters::ViewerTypeFormatter

  # child_index is provided by CDMDEXER; children are assigned the order in
  # which they were received from the CDM API
  - dest_path: child_index
    origin_path: child_index
    formatters: []

  # Attachments can appear below kaltura items or complex objects that
  # have an attachment specified in the parent item. Attachments offer
  # complimentary content for the featured item. A video about a paiting
  # might have a iiif image attachment that shows the painting, for example
  - dest_path: attachment
    origin_path: find
    formatters: []

  # Attachment format is a "viewer" format (iiif, pdf, etc). If this
  # field is missing, the UI code will not display an attachment
  - dest_path: attachment_format
    origin_path: /
    formatters:
      - Umedia::Formatters::AttachmentFormatter

  # We have both collection and item data in the index
  - dest_path: document_type
    origin_path: id
    formatters:
      - Umedia::Formatters::DocumentFormatter

  ###########################################
  # CONTENTdm record add dates (good for sorting by recency)
  ###########################################
  - dest_path: date_added
    origin_path: dmcreated
    formatters:
      - Umedia::Formatters::ToSolrDateFormatter

  - dest_path: date_added_sort
    origin_path: dmcreated
    formatters:
      - Umedia::Formatters::ToSolrDateFormatter

  - dest_path: date_modified
    origin_path: dmmodified
    formatters:
      - Umedia::Formatters::ToSolrDateFormatter

  ###########################################
  # Spanish language fields
  ###########################################
  - dest_path: es_title
    origin_path: sptitl
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: es_description
    origin_path: spdesc
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: es_notes
    origin_path: spaddi
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: es_types
    origin_path: spitea
    formatters:
      - CDMDEXER::StripFormatter
      - CDMDEXER::Titlieze
      - CDMDEXER::SplitFormatter
      - CDMDEXER::UniqueFormatter

  - dest_path: es_format
    origin_path: spitem
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: es_format_name
    origin_path: spitem
    formatters:
      - Umedia::Formatters::FormatNameFormatter
      - CDMDEXER::StripFormatter

  - dest_path: es_dimensions
    origin_path: spdime
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: es_subject
    formatters:
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: sploca

  - dest_path: es_country
    origin_path: spcoun
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: es_continent
    origin_path: spcont
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: es_language
    origin_path: splang
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter

  - dest_path: es_local_rights
    origin_path: splocb
    formatters:
      - CDMDEXER::StripFormatter

  - dest_path: es_rights_statement_uri
    origin_path: sprigh
    formatters:
      - CDMDEXER::StripFormatter

  ##########################################
  # IIIF support
  ##########################################
  - dest_path: iiif_manifest_url
    origin_path: /
    formatters:
      - Umedia::Formatters::IiifManifestUrlFormatter

  #- dest_path: iiif_manifest
  #  origin_path: /
  #  formatters:
  #    - Umedia::Formatters::IiifManifestFormatter
