### Default Gem Field mappings
---
field_mappings:
  -
    dest_path: location_llsi
    formatters:
      - CDMDEXER::LocationFormatter
    origin_path: /
  -
    dest_path: id
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: id
  -
    dest_path: setspec_ssi
    formatters:
      - CDMDEXER::AddSetSpecFormatter
      - CDMDEXER::SetSpecFormatter
    origin_path: /
  -
    dest_path: collection_name_ssi
    formatters:
      - CDMDEXER::AddSetSpecFormatter
      - CDMDEXER::CollectionNameFormatter
    origin_path: /
  -
    dest_path: collection_name_tei
    formatters:
      - CDMDEXER::AddSetSpecFormatter
      - CDMDEXER::CollectionNameFormatter
    origin_path: /
  -
    dest_path: collection_description_tesi
    formatters:
      - CDMDEXER::AddSetSpecFormatter
      - CDMDEXER::CollectionDescriptionFormatter
      - CDMDEXER::FilterBadCollections
    origin_path: /
  -
    dest_path: parent_collection_name_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: par
  -
    dest_path: parent_collection_name_tei
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: par
  -
    dest_path: parent_collection_description_tei
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: par
  -
    dest_path: title_tesi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: title
  -
    dest_path: title_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: title
  -
    dest_path: title_sort
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: title
  -
    dest_path: title_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: title
  -
    dest_path: contributor_teim
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: contri
  -
    dest_path: contributor_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: contri
  -
    dest_path: contributor_ssim
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: contri
  -
    dest_path: creator_tesi
    formatters:
      - CDMDEXER::JoinFormatter
      - CDMDEXER::StripFormatter
    origin_path: photog
  -
    dest_path: creator_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: photog
  -
    dest_path: creator_ssim
    formatters:
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: photog
  -
    dest_path: creator_sort
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: photog
  -
    dest_path: description_tei
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: descri
  -
    dest_path: description_ts
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: descri
  -
    dest_path: dat_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: dat
  -
    dest_path: dat_tesi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: dat
  -
    dest_path: dat_sort
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: dat
  -
    dest_path: publishing_agency_tei
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: publia
  -
    dest_path: publishing_agency_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: publia
  -
    dest_path: publishing_agency_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: publia
  -
    dest_path: dimensions_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: dimens
  -
    dest_path: topic_teim
    formatters:
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: genera
  -
    dest_path: topic_ssim
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: genera
  -
    dest_path: topic_unstem_search
    formatters:
      - CDMDEXER::StripSemicolonFormatter
      - CDMDEXER::StripFormatter
    origin_path: genera
  -
    dest_path: type_ssi
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::StripSemicolonFormatter
      - CDMDEXER::StripFormatter
    origin_path: type
  -
    dest_path: type_tesi
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::StripSemicolonFormatter
      - CDMDEXER::StripFormatter
    origin_path: type
  -
    dest_path: physical_format_ssi
    formatters:
      - CDMDEXER::StripSemicolonFormatter
    origin_path: physic
  -
    dest_path: physical_format_tesi
    formatters:
      - CDMDEXER::StripSemicolonFormatter
    origin_path: physic
  -
    dest_path: formal_subject_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: specif
  -
    dest_path: formal_subject_ssim
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: specif
  -
    dest_path: formal_subject_teim
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: specif
  -
    dest_path: subject_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: subjec
  -
    dest_path: subject_teim
    formatters:
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: subjec
  -
    dest_path: subject_ssim
    formatters:
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: subjec
  -
    dest_path: keyword_unstem_search
    formatters:
      - CDMDEXER::KeywordFormatter
      - CDMDEXER::Titlieze
      - CDMDEXER::UniqueFormatter
      - CDMDEXER::StripFormatter
    origin_path: /
  -
    dest_path: keyword_tesi
    formatters:
      - CDMDEXER::KeywordFormatter
      - CDMDEXER::Titlieze
      - CDMDEXER::UniqueFormatter
      - CDMDEXER::JoinFormatter
      - CDMDEXER::StripFormatter
    origin_path: /
  -
    dest_path: keyword_ssim
    formatters:
      - CDMDEXER::KeywordFormatter
      - CDMDEXER::Titlieze
      - CDMDEXER::UniqueFormatter
      - CDMDEXER::StripFormatter
    origin_path: /
  -
    dest_path: city_ssim
    formatters:
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: city
  -
    dest_path: city_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: city
  -
    dest_path: district_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: distri
  -
    dest_path: district_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: distri
  -
    dest_path: county_ssim
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: county
  -
    dest_path: county_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: county
  -
    dest_path: state_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: state
  -
    dest_path: state_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: state
  -
    dest_path: country_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: countr
  -
    dest_path: country_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: countr
  -
    dest_path: language_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: langua
  -
    dest_path: language_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: langua
  -
    dest_path: contributing_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: contra
  -
    dest_path: contributing_organization_tesi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: contra
  -
    dest_path: contributing_organization_ssi
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::StripFormatter
    origin_path: contra
  -
    dest_path: contact_information_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: contac
  -
    dest_path: rights_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: righta
  -
    dest_path: local_identifier_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: identi
  -
    dest_path: identifier_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: resour
  -
    dest_path: project_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: projec
  -
    dest_path: fiscal_sponsor_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: fiscal
  -
    dest_path: publisher_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: publis
  -
    dest_path: date_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: date
  -
    dest_path: format_tesi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: format
  -
    dest_path: digspa_ssi
    origin_path: digspa
  -
    dest_path: digspb_ssi
    origin_path: digspb
  -
    dest_path: digspc_ssi
    origin_path: digspc
  -
    dest_path: digspd_ssi
    origin_path: digspd
  -
    dest_path: digspe_ssi
    origin_path: digspe
  -
    dest_path: digspf_ssi
    origin_path: digspf
  -
    dest_path: digspg_ssi
    origin_path: digspg
  -
    dest_path: digsph_ssi
    origin_path: digsph
  -
    dest_path: digspi_ssi
    origin_path: digspi
  -
    dest_path: digspj_ssi
    origin_path: digspj
  -
    dest_path: digspk_ssi
    origin_path: digspk
  -
    dest_path: transcription_tesi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: transc
  -
    dest_path: translation_tesi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: transl
  -
    dest_path: fullrs_tesi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: fullrs
  -
    dest_path: find_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: find
  -
    dest_path: dmaccess_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: dmaccess
  -
    dest_path: dmimage_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: dmimage
  -
    dest_path: dmcreated_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: dmcreated
  -
    dest_path: dmmodified_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: dmmodified
  -
    dest_path: dmoclcno_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: dmoclcno
  -
    dest_path: restriction_code_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: restrictionCode
  -
    dest_path: cdmfilesize_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: cdmfilesize
  -
    dest_path: cdmfilesizeformatted_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: cdmfilesizeformatted
  -
    dest_path: cdmprintpdf_is
    formatters:
      - CDMDEXER::ToIFormatter
    origin_path: cdmprintpdf
  -
    dest_path: cdmhasocr_is
    formatters:
      - CDMDEXER::ToIFormatter
    origin_path: cdmhasocr
  -
    dest_path: cdmisnewspaper_is
    formatters:
      - CDMDEXER::ToIFormatter
    origin_path: cdmisnewspaper
  -
    dest_path: image_uri_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: image_uri
  -
    dest_path: record_type_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: record_type
  -
    dest_path: geographic_feature_ssim
    formatters:
      - CDMDEXER::Titlieze
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: geogra
  -
    dest_path: geographic_feature_teim
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: geogra
  -
    dest_path: geographic_feature_unstem_search
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: geogra
  -
    dest_path: geonam_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: geonam
  -
    dest_path: kaltura_audio_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: audio
  -
    dest_path: kaltura_audio_playlist_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: audioa
  -
    dest_path: kaltura_video_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: video
  -
    dest_path: kaltura_video_playlist_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: videoa
  -
    dest_path: coordinates_llsi
    formatters:
      - CDMDEXER::GeoNameID
      - CDMDEXER::GeoNameIDToJson
      - CDMDEXER::GeoNameToLocation
    origin_path: geonam
  -
    dest_path: placename_ssim
    formatters:
      - CDMDEXER::GeoNameID
      - CDMDEXER::GeoNameIDToJson
      - CDMDEXER::GeoNameToPlaceName
    origin_path: geonam
  -
    dest_path: placename_unstem_search
    formatters:
      - CDMDEXER::GeoNameID
      - CDMDEXER::GeoNameIDToJson
      - CDMDEXER::GeoNameToPlaceName
    origin_path: geonam
  -
    dest_path: table_ssim
    formatters:
      - CDMDEXER::StripFormatter
      - CDMDEXER::SplitFormatter
      - CDMDEXER::StripFormatter
    origin_path: table
  -
    dest_path: umedia_ssi
    formatters:
      - CDMDEXER::StripFormatter
    origin_path: umedia
  -
    dest_path: child_index
    formatters: []
    origin_path: child_index
