# kaltura.yml

default: &default
  url: <%= ENV.fetch('KALTURA_URL', 'https://cdnapisec.kaltura.com') %>
  partner_id: <%= ENV.fetch('KALTURA_PARTNER_ID', 1369852) %>
  sub_partner_id: <%= ENV.fetch('KALTURA_PARTNER_ID', 136985200) %>  
  uiconf_id: <%= ENV.fetch('KALTURA_UICONF_ID', 54071352) %>
  
development:
  <<: *default

publicdev:
  <<: *default

test:
  <<: *default

production:
  <<: *default
