# frozen_string_literal: true

module Umedia
  module Catalog
    module JsonBehaviors
      def full_json
        _, @document = search_service.fetch(params[:id])

        # Exclude dynamic fields using blacklight solr suffixes
        # and other fields generated by blacklight
        dynamic_field_suffixes = %w[_s _t _ss _ssi _ssi _ssim _tesi _tesim _tesimv _ts _txt_en_ascii]
        
        fields = @document._source.to_h.deep_dup.reject do |k,v|
          %w[_version_ timestamp].include?(k) || k.end_with?(*dynamic_field_suffixes)
        end

        render json: JSON.pretty_generate(fields.merge!(children_append).as_json)
      end

      def children_append
        {
          'children' => get_children['response']['docs']
        }
      end

      def get_children
        blacklight_solr.get('select', :params => child_params)
      end

      def child_params
        {
          :q => 'parent_id:' + @document.id.to_s,
          :rows => '50000',
          :hl => 'on',
          :sort => 'child_index asc', 
          'hl.method': 'original'
        }
      end

      def blacklight_solr
        Blacklight.default_index.connection
      end
    end
  end
end

